[build] 
  publish = "dist"
  command = "npm run build"


[[plugins]]
  package = "./netlify/plugins/contentful-data"

  [plugins.inputs]
    # Directory for the generated JSON data files to reside in
    dataDir = "data"
