[build] 
  publish = "dist"
  command = "echo no build yet"


[[plugins]]
  package = "./netlify/plugins/contentful-data"

  [plugins.inputs]

    # Directory for the generated JSON data files to reside
    dataFilePath = "src/data"

    # If the plugin fails, should it do so quietly or cancel the build?
    # "failBuild" | "failPlugin"
    fail = "failBuild"