[build] 
  publish = "dist"
  command = "echo no build yet"


[[plugins]]
  package = "./netlify/plugins/contentful-data"

  [plugins.inputs]
    # Directory for the generated JSON data files to reside in
    dataFilePath = "src/data"
