[build] 
  publish = "dist"
  command = "npm run build"

[[plugins]]
  # package = "../demo-restaurant-sites-data/plugins/contentful"

  package = "./node_modules/@netlify/demo-restaurant-sites-data/plugins/contentful"
  # Coming soon...
  # package = "./node_modules/@netlify/demo-restaurant-sites-data/plugins/sanity"
  # package = "./node_modules/@netlify/demo-restaurant-sites-data/plugins/airtable"

  [plugins.inputs]
    # Directory for the generated JSON data files to reside in
    dataDir = "data"
