[build] 
  publish = "dist"
  command = "npm run build"

[[plugins]]
  # package = "../plugins/demo-belly-data-contentful"
  package = "./netlify/plugins/contentful"

  [plugins.inputs]
    # Directory for the generated JSON data files to reside in
    dataDir = "data"
